# -*- coding: utf-8 -*-
"""Untitled110.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113HDclGMQxxmuqFgS7yVapd5oaQL4n2z
"""

from pipeline import run_pipeline
import joblib
import numpy as np
import os

MODEL_PATH = "best_model.pkl"


def ensure_model():
    """
    Проверяем — если модели нет, запускаем pipeline.
    """
    if not os.path.exists(MODEL_PATH):
        print("Модель не найдена. Запускаем pipeline...")
        run_pipeline()
    else:
        print("Модель уже существует.")


def start_app():
    print("=== Приложение запускается ===")

    ensure_model()

    while True:
        age = input("Введите возраст (или q для выхода): ")

        if age.lower() == "q":
            break

        age = int(age)

        model = joblib.load(MODEL_PATH)
        prediction = model.predict(np.array([[age]]))

        print("Прогноз дохода:", prediction[0])


if __name__ == "__main__":
    start_app()