# -*- coding: utf-8 -*-
"""Untitled112.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bN2WFbnsEUfLsrUgYBBVT-ZJAHEtsZu5
"""

#pip install pyinstaller
#pyinstaller --onefile app.py